# repos:
# - repo: local
#   hooks:
#     - id: black
#       name: black
#       entry: poetry run black .
#       pass_filenames: false
#       language: system
#       types: [python]
#       pass_filenames: false
#
#     - id: isort
#       name: isort
#       entry: poetry run isort .
#       language: system
#       types: [python]
#       pass_filenames: false
#
#     - id: flake8
#       name: flake8
#       entry: poetry run flake8 .
#       language: system
#       types: [python]
#       pass_filenames: false
