[tool.poetry]
name = "poetry_temp"
version = "0.1.0"
description = ""
authors = ["chernov.ig <che_test@test>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
numpy = "^1.22.3"
pandas = "^1.4.2"
matplotlib = "^3.5.1"
scikit-learn = "^1.0.2"
scipy = "^1.8.0"
ipykernel = "^6.13.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
